### ISSUE TITLE
Future of Pyzor?

### ISSUE THREAD

**Issue by AnAnalogGuy** [SpamExperts/pyzor#169]
As there is no discussion board available, i'm "mis-using" the defect reporting for a clarification question:

I got the impression Pyzor isn't actively maintained since quite some time. Does this mean, the software reached a maturity where it doesn't have to be updated again (i doubt this a bit reading about the issues with Python 3). Or do we have to consider this project to be abandoned? If so, why?

**Comment by mnalis** [comment]
Why would one call it abandoned, if both the client and officially listed servers perform their functions just fine on a day-to-day basis (and have been doing it for years)? Or am I missing something?

---

Whether there is interest to port its full functionality to a new language (python3 and [perl](https://cwiki.apache.org/confluence/display/SPAMASSASSIN/UsingPyzor) are two most commonly mentioned) is wholly another question, though. 

That perl one in SA 4.01 looks fine, although it does not implement 100% of the python2 pyzor functionality AFAICT.

**Comment by tonyandrewmeyer** [comment]
I can no longer speak for the project or for N-able, but I can give some background.

SpamExperts cared about improving pyzor for its own use, but also as one of the ways that the company could give back to the community, not just through the code but also the public server and data. We were trying to increase this (not just with Pyzor but other open source as well) over time. We did make improvements, although never as many as I hoped, and did spend a lot of time on improving the server performance rather than filtering improvements, unfortunately. We had plans for a lot more and some initial work was done.

When SpamExperts was acquired by SolarWinds priorities were different. Contributing to open-source was not a priority, and actually pretty difficult. Improving filtering performance (including via pyzor) was lower priority than a lot of other work, so everything here stagnated pretty quickly at that point. When SolarWinds split off N-able the email team went to N-able but little changed in this regard.

When I left N-able there were still many good people there, and that is likely still true. There were not many who would have both the desire and skillset to work on pyzor, and - based on my knowledge at the time - no way it would get time assigned in the foreseeable future.

For now, the public server still lives. I wouldn't expect this to continue indefinitely. There were challenges there in my time, when I had some influence and could advocate for it. My guess is that has only gotten more difficult.

I would not expect much to happen with the project while it is in N-able's hands.

A release would be good, and that's partly on me for not making it happen while I could 😞. The main (probably "master") code is newer than the latest release.

Python3 should work - we were definitely running under python3 (pypy3 I think) although it would have been an older 3, like 3.5 maybe (hence the ticket about deprecation warnings with newer 3). The released version is missing some of that. Updating would be trivial - PRs that were obviously correct *might* get accepted, e.g. ones that don't need official time from anyone at N-able and can just be reviewed and merged by people that care.

@mnalis is right that the client and public.pyzor.org do still work (for now), although you really need to install from Git not pypi.

Again, I can't speak for the project or N-able these days, so they could pipe up and say they do care and will dedicate time to it, but that is unlikely.

If you just want to use it, I'd suggest installing from Git. If you want to improve it, I'd suggest forking.

**Comment by AnAnalogGuy** [comment]
Thanks a lot @tonyandrewmeyer for the insights. 

My question - and this is also an answer to @mnalis reply - is to be understood in the context of how much current users should rely on Pyzor (as a software and as a service) being around und maintend in the future. From this perspective, it's always nice to get some kind of statement form the project about the future (i'm not asking for a release planing or similar) rather than a silent "fading away". Your personal view is very helpful in this regard.

**Comment by donici** [comment]
Thanks for bringing this to our attention and thanks @tonyandrewmeyer for providing the background. Pyzor improvements were lined up in our backlogs and we will soon start working on them. The move to Python3 already started and we'll soon have a release ready. 🤞
